version: "3.5"
services:

    nginx:
        image: nginx:alpine
        volumes:
            - ..:/app
            - ./nginx/nginx-swarm.conf:/etc/nginx/conf.d/default.conf
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.constraint-label=traefik-public
                - traefik.http.routers.${STACK_NAME}-http.rule=Host(`psw-crack.docker.localhost`)
                - traefik.http.routers.${STACK_NAME}-http.entrypoints=http
                - traefik.http.services.${STACK_NAME}.loadbalancer.server.port=80
        depends_on:
            - php
        networks:
            - traefik-public
            - app

    php:
        image: ${STACK_NAME}_php
        env_file:
            - .env
        environment:
            PHP_IDE_CONFIG: "serverName=php"
        user: 1000:1000
        networks:
            - app
        volumes:
            - ..:/app
            - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/php-ext-xdebug-alt.ini

    db:
        image: mysql:8.0.32
        volumes:
            - ./mysql/sql-initdb:/docker-entrypoint-initdb.d
            - db_data:/var/lib/mysql
        ports:
            - target: 3306
              published: $DB_PORT
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: $DB_DATABASE
            MYSQL_USER: $DB_USERNAME
            MYSQL_PASSWORD: $DB_PASSWORD
        networks:
            - app

networks:
    app:
    traefik-public:
        external: true

volumes:
    db_data:
