FROM node:18.20-alpine3.21
ARG api_url
ENV API_URL=${api_url}
ENV NODE_ENV=development
ARG port
ENV PORT=${port}
WORKDIR /app
RUN echo -e "PORT=${PORT}" >> /app/.env
RUN echo -e "HOST=0.0.0.0" >> /app/.env
RUN echo -e "API_URL=${API_URL}" >> /app/.env
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
EXPOSE 3001